bug 1669248: add dockerhub auth and conform to dockerflow
This ditches the deploy-dockerhub.sh script and adds the bits directly
to the CircleCI config file. It also changes it to conform to the
existing Dockerflow conventions.

This switches to using DOCKERHUB_REPO, DOCKER_USER, and DOCKER_PASS
variables. They'll be in the environment when CircleCI is running a job
based on this repo, but won't be available in the environment when
CircleCI is running a job based on a fork.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,16 +1,38 @@
+---
+# These environment variables must be set in CircleCI UI
+#
+# DOCKERHUB_REPO - docker hub repo, format: <username>/<repo>
+# DOCKER_USER    - login info for docker hub
+# DOCKER_PASS
 version: 2.1
 jobs:
   build_test_publish:
     docker:
       - image: mozilla/cidockerbases:docker-latest
+        auth:
+          username: $DOCKER_USER
+          password: $DOCKER_PASS
     working_directory: ~/tecken
 
     steps:
+      - run:
+          name: Host info
+          command: uname -v
+
       - checkout
 
       - setup_remote_docker:
           docker_layer_caching: true
           version: 19.03.13
+
+      - run:
+          name: Login to Dockerhub
+          command: |
+            if [ "${DOCKER_USER}" == "" ] || [ "${DOCKER_PASS}" == "" ]; then
+              echo "Skipping Login to Dockerhub, credentials not available."
+            else
+              echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin
+            fi
 
       - run:
           name: Create version.json
@@ -55,13 +77,42 @@ jobs:
           name: Push to Dockerhub
           working_directory: ~/tecken
           command: |
-            # set DOCKER_DEPLOY=true in Circle UI to push to Dockerhub
-            DOCKER_DEPLOY="${DOCKER_DEPLOY:-false}"
-            if [ "${CIRCLE_BRANCH}" == "main" ]; then
-              bin/ci/deploy-dockerhub.sh latest
-            fi
-            if [ -n "${CIRCLE_TAG}" ]; then
-              bin/ci/deploy-dockerhub.sh "$CIRCLE_TAG"
+            function retry {
+                set +e
+                local n=0
+                local max=3
+                while true; do
+                "$@" && break || {
+                  if [[ $n -lt $max ]]; then
+                    ((n++))
+                    echo "Command failed. Attempt $n/$max:"
+                  else
+                    echo "Failed after $n attempts."
+                    exit 1
+                  fi
+                }
+                done
+                set -e
+            }
+
+            export LOCAL_IMAGE="tecken:build"
+
+            if [ "${DOCKER_USER}" == "" ] || [ "${DOCKER_PASS}" == "" ]; then
+              echo "Skipping Login to Dockerhub, credentials not available."
+            else
+              echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin
+
+              if [ "${CIRCLE_BRANCH}" == "main" ]; then
+                # deploy latest on main branch updates
+                docker tag "${LOCAL_IMAGE}" "${DOCKERHUB_REPO}:latest"
+                retry docker push "${DOCKERHUB_REPO}:latest"
+              elif  [ ! -z "${CIRCLE_TAG}" ]; then
+                # deploy a release tag
+                echo "${DOCKERHUB_REPO}:${CIRCLE_TAG}"
+                docker tag "${LOCAL_IMAGE}" "${DOCKERHUB_REPO}:${CIRCLE_TAG}"
+                docker images
+                retry docker push "${DOCKERHUB_REPO}:${CIRCLE_TAG}"
+              fi
             fi
 
 workflows:
